services:
  db:
    image: postgres:14.12
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./tasks_app
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - ./tasks_app:/tasks_app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # Because you created the env file before docker-compose

  frontend:
    build: ./tasks_gui
    ports:
      - "80:80"
    depends_on:
      - backend
      

volumes:
  postgres_data: