# Generated by Django 5.0.6 on 2024-07-31 08:20

import django.db.models.deletion
import task.models
from django.db import migrations, models
from django.db import connection

def create_default_tab(apps, schema_editor):
    Tab = apps.get_model('task', 'Tab')
    if not Tab.objects.filter(id=1).exists():
        Tab.objects.create(id=1, tab_id='default_tab_id', tab_name='Default Tab')

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.CharField(auto_created=True, default=task.models.get_random_string, max_length=25, unique=True)),
                ('tab_name', models.CharField(default='untitled', max_length=50)),
            ],
        ),
        migrations.RunPython(create_default_tab, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='tasks',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.tab'),
            preserve_default=False,
        ),
    ]
